name: "tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_ACCESS_TOKEN: ${{ secrets.FLAKINESS_ACCESS_TOKEN }}
  FLAKINESS_ENDPOINT: "https://dev.flakiness.io"

jobs:
  test_linux:
    name: ${{ matrix.os }} (Node.js ${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        node-version: [20]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
    - run: npx flakiness upload-playwright-json ./test-results.json
      if: ${{ !cancelled() }}
      shell: bash

